grpc:
  client:
    grpc-accounts-loans-service:
      address: static://localhost:9000
      default-load-balancing-policy: round_robin
      negotiationType: plainText
#    GLOBAL:
#      address: static://localhost:9000
#      default-load-balancing-policy: round_robin

logging:
  level:
    io.grpc.LoadBalancerProvider: DEBUG